apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-internal
  labels:
    app: elastic
    role: master
spec:
  selector:
    app: elastic
    deployment: production
  clusterIP: None
  ports:
    - name: http
      port: 9200
      protocol: TCP

