apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels: 
    app: kibana
    role: visual
spec:
  selector:
    app: kibana
    role: visual
  type: LoadBalancer
  ports:
    - name: accessport
      port: 5601
      targetPort: 5601

